language: r
sudo: true
warnings_are_errors: false
cache: packages
apt_packages:
  - libudunits2-dev

r_packages:
  - roxygen2
  - rmarkdown

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
