language: R
sudo: false
cache: packages
r:
  - release
  - devel
  #- oldrel

addons:
  apt:
    packages:
      - libudunits2-dev

r_github_packages:
  - r-lib/covr@v3.0.1

after_success:
  - Rscript -e 'covr::codecov()'
