language: R
sudo: false
cache: packages
r:
  - release
  - devel
  #- oldrel

addons:
  apt:
    packages:
      - libudunits2-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
