language: R
sudo: false
cache: packages
r:
  - release
  - devel
  #- oldrel

addons:
  apt:
    packages:
      - libudunits2-dev

r_github_packages:
  - r-lib/covr
  - r-quantities/errors

script:
  - git clone https://github.com/r-quantities/quantities.git
  - bash quantities/scripts/check_with_quantities.sh

after_success:
  - Rscript -e 'covr::codecov()'
